export const PROVINCIAS_CIUDADES: Record<string, string[]> = {
  'Álava': ['Vitoria-Gasteiz', 'Llodio', 'Amurrio', 'Salvatierra', 'Laudio'],
  'Albacete': ['Albacete', 'Hellín', 'Almansa', 'Villarrobledo', 'La Roda', 'Caudete'],
  'Alicante': ['Alicante', 'Elche', 'Torrevieja', 'Orihuela', 'Benidorm', 'Alcoy', 'Elda', 'Petrer', 'San Vicente del Raspeig', 'Villena', 'Dénia', 'Calp', 'Ibi', 'Crevillent', 'Novelda', 'Sant Joan d\'Alacant', 'Mutxamel', 'El Campello', 'Santa Pola', 'Guardamar del Segura', 'Torredembarra', 'Xàbia', 'Altea', 'Rojales', 'Cox', 'Aspe', 'Monforte del Cid', 'Bigastro', 'Dolores', 'Pilar de la Horadada', 'Pego'],
  'Almería': ['Almería', 'El Ejido', 'Roquetas de Mar', 'Vícar', 'Níjar', 'Adra', 'Vera', 'Berja'],
  'Asturias': ['Oviedo', 'Gijón', 'Avilés', 'Siero', 'Langreo', 'Mieres', 'Castrillón', 'Carreño', 'Gozón', 'Valdés'],
  'Ávila': ['Ávila', 'Arévalo', 'Arenas de San Pedro'],
  'Badajoz': ['Badajoz', 'Mérida', 'Don Benito', 'Villanueva de la Serena', 'Almendralejo', 'Zafra', 'Jerez de los Caballeros'],
  'Baleares': ['Palma', 'Calvià', 'Manacor', 'Llucmajor', 'Marratxí', 'Ibiza', 'Santa Eulàlia des Riu', 'Mahón', 'Ciutadella de Menorca'],
  'Barcelona': ['Barcelona', 'L\'Hospitalet de Llobregat', 'Badalona', 'Terrassa', 'Sabadell', 'Mataró', 'Santa Coloma de Gramenet', 'Cornellà de Llobregat', 'Rubí', 'Castelldefels', 'Granollers', 'Cerdanyola del Vallès', 'Sant Cugat del Vallès', 'Gavà', 'Vilanova i la Geltrú', 'Esplugues de Llobregat', 'El Prat de Llobregat', 'Igualada', 'Manresa', 'Vic'],
  'Burgos': ['Burgos', 'Miranda de Ebro', 'Aranda de Duero'],
  'Cáceres': ['Cáceres', 'Plasencia', 'Navalmoral de la Mata'],
  'Cádiz': ['Cádiz', 'Jerez de la Frontera', 'Algeciras', 'San Fernando', 'El Puerto de Santa María', 'Sanlúcar de Barrameda', 'La Línea de la Concepción', 'Chiclana de la Frontera', 'Rota'],
  'Cantabria': ['Santander', 'Torrelavega', 'Castro-Urdiales', 'Camargo', 'Piélagos', 'El Astillero'],
  'Castellón': ['Castellón de la Plana', 'Vila-real', 'Burriana', 'Benicàssim', 'Vinaròs', 'Nules'],
  'Ceuta': ['Ceuta'],
  'Ciudad Real': ['Ciudad Real', 'Puertollano', 'Tomelloso', 'Alcázar de San Juan', 'Valdepeñas', 'Manzanares'],
  'Córdoba': ['Córdoba', 'Lucena', 'Cabra', 'Montilla', 'Priego de Córdoba', 'Pozoblanco'],
  'A Coruña': ['A Coruña', 'Vigo', 'Ferrol', 'Santiago de Compostela', 'Narón', 'Oleiros', 'Arteixo', 'Culleredo', 'Cambre', 'Boiro'],
  'Cuenca': ['Cuenca', 'Tarancón'],
  'Girona': ['Girona', 'Lloret de Mar', 'Blanes', 'Figueres', 'Salt', 'Olot'],
  'Granada': ['Granada', 'Motril', 'Almuñécar', 'Maracena', 'Armilla', 'Albolote', 'Loja'],
  'Guadalajara': ['Guadalajara', 'Azuqueca de Henares', 'Cabanillas del Campo'],
  'Gipuzkoa': ['San Sebastián', 'Irun', 'Errenteria', 'Zarautz', 'Eibar', 'Arrasate-Mondragón', 'Hernani'],
  'Huelva': ['Huelva', 'Lepe', 'Almonte', 'Isla Cristina', 'Ayamonte'],
  'Huesca': ['Huesca', 'Monzón', 'Barbastro', 'Jaca'],
  'Jaén': ['Jaén', 'Linares', 'Andújar', 'Úbeda', 'Baeza', 'Martos'],
  'León': ['León', 'Ponferrada', 'San Andrés del Rabanedo', 'Villaquilambre'],
  'Lleida': ['Lleida', 'Mollerussa', 'Tàrrega'],
  'La Rioja': ['Logroño', 'Calahorra', 'Arnedo', 'Haro'],
  'Lugo': ['Lugo', 'Monforte de Lemos', 'Vilalba'],
  'Madrid': ['Madrid', 'Móstoles', 'Alcalá de Henares', 'Fuenlabrada', 'Leganés', 'Getafe', 'Alcorcón', 'Torrejón de Ardoz', 'Parla', 'Alcobendas', 'Rivas-Vaciamadrid', 'Pozuelo de Alarcón', 'Collado Villalba', 'Las Rozas de Madrid', 'San Sebastián de los Reyes', 'Majadahonda', 'Valdemoro', 'Coslada', 'Tres Cantos', 'Aranjuez', 'Arganda del Rey'],
  'Málaga': ['Málaga', 'Marbella', 'Vélez-Málaga', 'Fuengirola', 'Torremolinos', 'Benalmádena', 'Mijas', 'Antequera', 'Estepona', 'Nerja', 'Ronda'],
  'Melilla': ['Melilla'],
  'Murcia': ['Murcia', 'Cartagena', 'Lorca', 'Molina de Segura', 'Alcantarilla', 'San Javier', 'Torre-Pacheco', 'Mazarrón', 'Águilas', 'Yecla', 'Jumilla'],
  'Navarra': ['Pamplona', 'Tudela', 'Barañáin', 'Burlada', 'Estella-Lizarra'],
  'Ourense': ['Ourense', 'Verín', 'O Barco de Valdeorras'],
  'Palencia': ['Palencia', 'Aguilar de Campoo'],
  'Las Palmas': ['Las Palmas de Gran Canaria', 'Telde', 'Arrecife', 'Puerto del Rosario', 'Arucas', 'Santa Lucía de Tirajana'],
  'Pontevedra': ['Vigo', 'Pontevedra', 'Vilagarcía de Arousa', 'Redondela', 'Cangas', 'Marín', 'Moaña'],
  'Salamanca': ['Salamanca', 'Béjar', 'Santa Marta de Tormes'],
  'Santa Cruz de Tenerife': ['Santa Cruz de Tenerife', 'San Cristóbal de La Laguna', 'Arona', 'Adeje', 'Los Llanos de Aridane', 'Granadilla de Abona'],
  'Segovia': ['Segovia', 'Cuéllar'],
  'Sevilla': ['Sevilla', 'Dos Hermanas', 'Alcalá de Guadaíra', 'Jerez de la Frontera', 'Mairena del Aljarafe', 'Utrera', 'La Rinconada', 'Écija', 'Carmona', 'Bormujos'],
  'Soria': ['Soria'],
  'Tarragona': ['Tarragona', 'Reus', 'Tortosa', 'El Vendrell', 'Salou', 'Cambrils'],
  'Teruel': ['Teruel', 'Alcañiz'],
  'Toledo': ['Toledo', 'Talavera de la Reina', 'Illescas', 'Madridejos'],
  'Valencia': ['Valencia', 'Torrent', 'Paterna', 'Mislata', 'Burjassot', 'Gandía', 'Sagunto', 'Aldaia', 'Manises', 'Alaquàs', 'Xirivella', 'Alzira', 'Sueca', 'Ontinyent', 'Xàtiva'],
  'Valladolid': ['Valladolid', 'Medina del Campo', 'Laguna de Duero', 'Arroyo de la Encomienda'],
  'Bizkaia': ['Bilbao', 'Barakaldo', 'Getxo', 'Basauri', 'Leioa', 'Santurtzi', 'Portugalete', 'Sestao', 'Durango'],
  'Zamora': ['Zamora', 'Benavente'],
  'Zaragoza': ['Zaragoza', 'Calatayud', 'Utebo', 'Cuarte de Huerva', 'Ejea de los Caballeros'],
}

export const PROVINCIAS = Object.keys(PROVINCIAS_CIUDADES).sort()
